"""empty message

Revision ID: 2996a6272da3
Revises: cea3688b0140
Create Date: 2024-11-25 13:10:52.978419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2996a6272da3'
down_revision = 'cea3688b0140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('taskname', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('task_author', sa.String(length=140), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=140), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=140), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('complete_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_complete_date'), ['complete_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('school_tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('school_tracker', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_timestamp'))
        batch_op.drop_index(batch_op.f('ix_task_due_date'))
        batch_op.drop_index(batch_op.f('ix_task_complete_date'))

    op.drop_table('task')
    # ### end Alembic commands ###
