"""empty message

Revision ID: b3524483f416
Revises: a9085b60c469
Create Date: 2024-11-27 00:54:23.497233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3524483f416'
down_revision = 'a9085b60c469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scorecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_focus_area', sa.String(length=100), nullable=False),
    sa.Column('strategic_objective', sa.String(length=200), nullable=False),
    sa.Column('performance_measure', sa.String(length=200), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('employee_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scorecard')
    # ### end Alembic commands ###
