"""Initial migration

Revision ID: cea3688b0140
Revises: ea5fb6d569db
Create Date: 2024-11-25 06:54:37.645890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea3688b0140'
down_revision = 'ea5fb6d569db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schoolname', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('computers', sa.Integer(), nullable=True),
    sa.Column('internet', sa.String(length=255), nullable=True),
    sa.Column('lab', sa.String(length=255), nullable=True),
    sa.Column('installed', sa.String(length=255), nullable=True),
    sa.Column('scheduled_visit', sa.String(length=255), nullable=True),
    sa.Column('tech_ready', sa.String(length=255), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('school_contact', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_tracker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_tracker_installation_date'), ['installation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_tracker_schoolname'), ['schoolname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_tracker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_tracker_schoolname'))
        batch_op.drop_index(batch_op.f('ix_school_tracker_installation_date'))

    op.drop_table('school_tracker')
    # ### end Alembic commands ###
